### ISSUE TITLE
Problema de concepto simple.

### ISSUE THREAD

**Issue by InsoltechFernando** [Panesoft/insoltech-gps#8]
## Estoy intentando llamar a la funcion: processRequestClient que esta en service-impl ->.. >DispatcherSocketServiceImpl.java

Desde Socket>...>main.java
import com.hcsinergia.delver.service.impl.DispatcherSocketServiceImpl;
....

public final class Main {
private static DispatcherSocketServiceImpl DispatcherSocketServiceI;

...
}

public void run() {
....
String StrDatos="Hola";
result = DispatcherSocketServiceI.processRequestClient(StrDatosSIM);

---

Exception in thread "Thread-1" java.lang.NullPointerEception
  at ... Main$handler.run(Main.java

**Comment by lvasconez** [comment]
DispatcherSocketServiceImpl dispatcherSocketServiceImpl = new DispatcherSocketServiceImpl();
dispatcherSocketServiceImpl.processRequestClient(StrDatosSIM);
